"""empty message

Revision ID: 222be77c22d0
Revises: 6a0902f5eccd
Create Date: 2025-10-28 17:03:50.635169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "222be77c22d0"
# down_revision: Union[str, Sequence[str], None] = "6a0902f5eccd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goal_respondents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal_respondents",
        sa.Column("goal_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("goal_respondents_employee_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["goals.id"], name=op.f("goal_respondents_goal_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "goal_id", "employee_id", name=op.f("goal_respondents_pkey")
        ),
    )
    # ### end Alembic commands ###
