"""Update 1.1

Revision ID: 6a0902f5eccd
Revises: df97d096656c
Create Date: 2025-10-27 12:50:40.065725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0902f5eccd'
down_revision: Union[str, Sequence[str], None] = 'df97d096656c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
