"""empty message

Revision ID: df97d096656c
Revises: fb41a8ccb21a
Create Date: 2025-10-27 12:45:28.601473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df97d096656c'
down_revision: Union[str, Sequence[str], None] = 'fb41a8ccb21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    # ### end Alembic commands ###
